### ISSUE TITLE
Angular app: babel preset missing?

### ISSUE THREAD

**Issue by tomzemp** [pepfar-datim/datim-mechanism-finder#28]
I got this error when trying to run current angular version of datim-mechanism-finder from the `/current` directory

```ERROR in ./src/app.js
Module build failed: Error: Couldn't find preset "es2015" relative to directory "/Users/thomaszemp/Documents/github/datim-mechanism-finder"
    at /Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/options/option-manager.js:292:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/options/option-manager.js:274:20)
    at OptionManager.mergePresets (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/options/option-manager.js:263:10)
    at OptionManager.mergeOptions (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/options/option-manager.js:248:14)
    at OptionManager.init (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/options/option-manager.js:367:12)
    at File.initOptions (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-loader/lib/index.js:38:20)
    at Object.module.exports (/Users/thomaszemp/Documents/github/datim-mechanism-finder/current/node_modules/babel-loader/lib/index.js:133:12)```

**Comment by tomzemp** [comment]
After looking around and trying various things, I fixed things by adding a file titled `.babelrc` to the root (`/current` directory)

with the following contents:

```{
  "presets": ["es2015"]
}```
